# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rE0oS53iGTWPpSkwTlLWH4LvDdIkZ5sT
"""

!pip install fuzzywuzzy

from fuzzywuzzy import process

# Expanded chatbot responses with more questions
responses = {
    # Greetings
    "hi": "Hello! How can I assist you today?",
    "hello": "Hi there! How can I help?",
    "hey there": "Hey! What do you need assistance with?",

    # Order Status
    "i want to check my order status": "Please provide your order number to check the status.",
    "where is my order": "Please share your order number to track your order.",
    "track my order": "You can track your order using the tracking link sent to your email.",

    # Refund & Cancellation
    "what is your refund policy": "Our refund policy allows returns within 30 days with proof of purchase.",
    "how can i return an item": "You can return items by visiting our return center or contacting support.",
    "i want to cancel my order": "You can cancel your order within 24 hours of purchase. Would you like to proceed?",

    # Payment Issues
    "i'm facing a payment issue": "Please check your payment method or try again later. Contact support if needed.",
    "why was my payment declined": "Payment may be declined due to insufficient funds or incorrect details. Try again or contact your bank.",
    "": "Yes, we accept all major credit and debit cards.",

    # Delivery & Shipping
    "how long does delivery take": "Standard delivery takes 5-7 business days. Express delivery takes 2-3 days.",
    "what are the shipping charges": "Shipping charges vary based on location. Please check our shipping policy page.",
    "do you offer express delivery": "Yes, we offer express delivery for an extra charge.",

    # Support & Contact
    "how can i contact customer support": "You can reach support at support@example.com or call +1-800-555-1234.",
    "give me your customer care number": "Our customer care number is +1-800-555-1234.",
    "where is your office located": "Our office is located in New York, USA.",

    # Miscellaneous
    "tell me a joke": "Why don’t skeletons fight each other? Because they don’t have the guts! 😂",
    "goodbye": "Goodbye! Have a great day!",
    "thanks for your help": "You're welcome! Happy to assist!"
}

# Function to find the best match for user input
def get_response(user_input):
    user_input = user_input.lower()
    best_match, score = process.extractOne(user_input, responses.keys())

    if score > 60:  # Accepts match if confidence > 60%
        return responses[best_match]
    else:
        return "I'm sorry, I don't understand. Can you rephrase your question?"

# Simple chatbot loop
while True:
    user_message = input("You: ")

    if user_message.lower() in ["exit", "quit", "bye"]:
        print("Bot: Goodbye! Have a great day!")
        break

    bot_response = get_response(user_message)
    print(f"Bot: {bot_response}")